"""add proposals table

Revision ID: 05573b31db68
Revises: 5e278b90326b
Create Date: 2026-06-15 18:43:23.007453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05573b31db68'
down_revision: Union[str, None] = '5e278b90326b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('doc_id', sa.String(length=50), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('doc_format', sa.String(length=50), nullable=True),
    sa.Column('proposal_title', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_contact', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('our_company_name', sa.String(length=255), nullable=True),
    sa.Column('our_company_address', sa.Text(), nullable=True),
    sa.Column('our_company_email', sa.String(length=255), nullable=True),
    sa.Column('our_company_tax_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('show_timeline', sa.Boolean(), nullable=True),
    sa.Column('apply_tax', sa.Boolean(), nullable=True),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('sign_name', sa.String(length=255), nullable=True),
    sa.Column('sign_title', sa.String(length=255), nullable=True),
    sa.Column('sign_image', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    # ### end Alembic commands ###
