"""initial_schema_with_capabilities

Revision ID: 08f194817a84
Revises: 
Create Date: 2026-06-09 02:06:45.626820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f194817a84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('capability_id')
    )
    op.create_index(op.f('ix_capabilities_token'), 'capabilities', ['token'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('role_tier', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=255), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.capability_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('attached_task_id', sa.String(length=36), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['attached_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_code_snippet', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###

    # Create audit_logs table
    op.execute("""
        CREATE TABLE audit_logs (
            log_id UUID PRIMARY KEY,
            table_name VARCHAR NOT NULL,
            record_id UUID NOT NULL,
            action VARCHAR NOT NULL,
            old_data JSONB,
            new_data JSONB,
            changed_by VARCHAR(36) REFERENCES users(user_id),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    """)

    # Create trigger function to log changes
    op.execute("""
        CREATE OR REPLACE FUNCTION log_table_changes()
        RETURNS TRIGGER AS $$
        DECLARE
            v_old_data JSONB := NULL;
            v_new_data JSONB := NULL;
            v_record_id UUID := NULL;
            v_changed_by VARCHAR(36) := NULL;
            v_action VARCHAR := TG_OP;
        BEGIN
            v_changed_by := NULLIF(current_setting('app.current_user_id', true), '');

            IF TG_OP = 'INSERT' THEN
                v_new_data := to_jsonb(NEW);
                v_record_id := NEW.task_id::uuid;
            ELSIF TG_OP = 'UPDATE' THEN
                v_old_data := to_jsonb(OLD);
                v_new_data := to_jsonb(NEW);
                v_record_id := NEW.task_id::uuid;
            ELSIF TG_OP = 'DELETE' THEN
                v_old_data := to_jsonb(OLD);
                v_record_id := OLD.task_id::uuid;
            END IF;

            INSERT INTO audit_logs (
                log_id,
                table_name,
                record_id,
                action,
                old_data,
                new_data,
                changed_by,
                created_at
            ) VALUES (
                gen_random_uuid(),
                TG_TABLE_NAME,
                v_record_id,
                v_action,
                v_old_data,
                v_new_data,
                v_changed_by,
                CURRENT_TIMESTAMP
            );

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            ELSE
                RETURN NEW;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Attach trigger to tasks table
    op.execute("""
        CREATE TRIGGER tasks_audit_trigger
        AFTER INSERT OR UPDATE OR DELETE ON tasks
        FOR EACH ROW
        EXECUTE FUNCTION log_table_changes();
    """)


def downgrade() -> None:
    # Drop audit logs trigger, function, and table
    op.execute("DROP TRIGGER IF EXISTS tasks_audit_trigger ON tasks;")
    op.execute("DROP FUNCTION IF EXISTS log_table_changes();")
    op.execute("DROP TABLE IF EXISTS audit_logs;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('channels')
    op.drop_table('user_capabilities')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index(op.f('ix_capabilities_token'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
