"""add_org_metadata_to_user

Revision ID: 5e278b90326b
Revises: 4e2264f9f8e6
Create Date: 2026-06-10 01:51:51.743124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e278b90326b'
down_revision: Union[str, None] = '4e2264f9f8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sub_department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('functional_role', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('specialization', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('seniority_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'seniority_level')
    op.drop_column('users', 'specialization')
    op.drop_column('users', 'functional_role')
    op.drop_column('users', 'sub_department')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
