"""add_task_meta_and_scheduling

Revision ID: 6d62aa602c3d
Revises: 9d07bbf84baf
Create Date: 2026-06-10 01:08:20.646693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d62aa602c3d'
down_revision: Union[str, None] = '9d07bbf84baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('industry_meta', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'industry_meta')
    # ### end Alembic commands ###
