"""add_client_id_and_rls

Revision ID: 9d07bbf84baf
Revises: 08f194817a84
Create Date: 2026-06-09 18:47:28.327964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d07bbf84baf'
down_revision: Union[str, None] = '08f194817a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['client_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Force enable RLS and create policies on PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TABLE projects ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;")

        # Create security policy for projects
        op.execute("""
            CREATE POLICY tenant_isolation_projects ON projects 
            FOR ALL 
            USING (
                current_setting('app.current_role', true) IN ('CEO', 'Lead', 'Employee') 
                OR client_id::UUID = current_setting('app.current_user_id', true)::UUID
            );
        """)

        # Create security policy for tasks that inherits the project's client authorization
        op.execute("""
            CREATE POLICY tenant_isolation_tasks ON tasks 
            FOR ALL 
            USING (
                current_setting('app.current_role', true) IN ('CEO', 'Lead', 'Employee') 
                OR project_id IN (
                    SELECT project_id FROM projects 
                    WHERE client_id::UUID = current_setting('app.current_user_id', true)::UUID
                )
            );
        """)


def downgrade() -> None:
    # Cleanup Protocol: reverse security measures on PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("DROP POLICY IF EXISTS tenant_isolation_tasks ON tasks;")
        op.execute("DROP POLICY IF EXISTS tenant_isolation_projects ON projects;")
        op.execute("ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE projects DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_client_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'client_id')
    # ### end Alembic commands ###
