"""add_leads_table

Revision ID: ad7603305ab3
Revises: 6d62aa602c3d
Create Date: 2026-06-10 01:21:33.917816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad7603305ab3'
down_revision: Union[str, None] = '6d62aa602c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'leads',
        sa.Column('lead_id', sa.String(length=36), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('raw_payload', sa.JSON(), nullable=True),
        sa.Column('normalized_data', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('assigned_to', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('lead_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
